version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - default-jdk
    - maven
  jobs:
    pre_build:
      - mvn --batch-mode compile
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: docs/requirements.txt